# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caa4da4598b88252950a39c1dc7c9c14e4b36c1556224d58fd309ec8e6af7c3fa3a7bb07ca6aea442424127a7c54f931f0070c47bb6f04a96655cd3afb82534b

test:
  secret_key_base: 39f4dcdc1c48f926134d0311aa1f4960b82ce977d487e7d1361d0e858cf6c750162b37c0c0ee9466d49b3b96dfdeb97d98aa4966b6561733191e5de201dc07fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
